name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # You can adjust this to the version you're using

    # Install dependencies
    # Use npm ci to install dependencies from package-lock.json
    - name: Install dependencies
      run: |
        cd frontend 
        npm ci

    # Run the build
    - name: Build the project
      run: npm run start

    # Run tests
    - name: Run tests
      run: npm test -- --ci --coverage  # Run tests in CI mode

    # Optionally, upload code coverage report (you can skip this if not using codecov)
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v3
    #   if: success()
    #   with:
    #     file: ./coverage/lcov-report/index.html  # Path to your coverage report (adjust if needed)
